### ISSUE TITLE
generate_tfrecord.py komutu TypeError: expected bytes, Descriptor found hatasını veriyor

### ISSUE THREAD

**Issue by poyrazaktas** [maacofficial/tensorflow-train-object-detection-classiffier-tutorial#2]
Merhabalar,
İlk önce bu yararlı yazınız için teşekkür ederim.
Dediğiniz adımları sırasıyla youtube videosundan takip ediyorum farklı hiçbir şey yapmadım.
Lakin kendi verimi xml_to_csv'ye çevirken de [hata](https://stackoverflow.com/questions/56244921/why-do-i-keep-getting-child-out-of-range-error) almıştım ama çözdüm.

**Bu komutu çalıştırdığımda :**
> python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record

**Böyle bir hata alıyorum :**
> Traceback (most recent call last):
>   File "generate_tfrecord.py", line 17, in <module>
>     import tensorflow as tf
>   File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
>     from tensorflow.core.framework.graph_pb2 import *
>   File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 10, in <module>
>     from google.protobuf import descriptor_pb2
>   File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\descriptor_pb2.py", line 1839, in <module>
>     __module__ = 'google.protobuf.descriptor_pb2'
> TypeError: expected bytes, Descriptor found

Yardımcı olursanız çok sevinirim.

**Comment by maacofficial** [comment]
Merhaba ne demek rica ederim. Tensorflow 1.5 sürümünü kurduğunuzdan lütfen emin olun.Tekrar kurmak için:
cpu kullanıyorsanız
`pip uninstall tensorflow`
gpu kullanıyorsanız
`pip uninstall tensorflow-gpu`
Tekrar kurmak için 
`pip install --ignore-installed --upgrade tensorflow==1.5.0`

**Comment by maacofficial** [comment]
> Merhabalar,
> İlk önce bu yararlı yazınız için teşekkür ederim.
> Dediğiniz adımları sırasıyla youtube videosundan takip ediyorum farklı hiçbir şey yapmadım.
> Lakin kendi verimi xml_to_csv'ye çevirken de [hata](https://stackoverflow.com/questions/56244921/why-do-i-keep-getting-child-out-of-range-error) almıştım ama çözdüm.
> 
> **Bu komutu çalıştırdığımda :**
> 
> > python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record
> 
> **Böyle bir hata alıyorum :**
> 
> > Traceback (most recent call last):
> > File "generate_tfrecord.py", line 17, in 
> > import tensorflow as tf
> > File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow__init__.py", line 24, in 
> > from tensorflow.python import *
> > File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python__init__.py", line 52, in 
> > from tensorflow.core.framework.graph_pb2 import *
> > File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 10, in 
> > from google.protobuf import descriptor_pb2
> > File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\descriptor_pb2.py", line 1839, in 
> > **module** = 'google.protobuf.descriptor_pb2'
> > TypeError: expected bytes, Descriptor found
> 
> Yardımcı olursanız çok sevinirim.

Çözdüyseniz belki farklı şekilde çözmüş olabilirsiniz yine böyle bir hatayla karşılaşan birisine faydalı olma amacıyla çözüm yolunu atar mısınız?

**Comment by poyrazaktas** [comment]
Öncelikle cevap verdiğiniz için çok teşekkür ederim. Repodaki adımları birebir izleme rağmen hata alıyordum fakat dediğiniz adımları CPU kullandığım için
`pip uninstall tensorflow`
`pip install --ignore-installed --upgrade tensorflow==1.5.0`
şeklinde yaptım ardından,

> python generate_tfrecord.py --csv_input=images\train_labels.csv --image_dir=images\train --output_path=train.record

komutunu çalıştırdım ve sorun çözüldü tekrardan teşekkür ederim.
İssue'yu kapatabilirsiniz.
